@token = 4|gewfjjFrMSzo7XpQ1D7PfiX6dSZb8LDs4c9rXG5Qec885528

### =====================================
### REGISTER
### POST /api/register
### =====================================

POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "negocio":"Ferreteria El Centro",
    "direccion":"Calle 1",
    "telefono":"77777777",

    "nombre":"Carlos",
    "email":"carlos@mail.com",
    "password":"123456"
}

### =====================================
### LOGIN
### POST /api/login
### =====================================

POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@test.com",
    "password": "123456"
}


### =====================================
### PERFIL DEL USUARIO
### GET /api/profile
### =====================================

GET http://127.0.0.1:8000/api/profile
Accept: application/json
Authorization: Bearer {{token}}


### =====================================
### CAMBIAR CONTRASEÑA
### PUT /api/change-password
### =====================================

PUT http://127.0.0.1:8000/api/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "current_password": "1234567890",
    "new_password": "987654321",
    "new_password_confirmation": "987654321"
}


### =====================================
### LOGOUT
### POST /api/logout
### =====================================

POST http://127.0.0.1:8000/api/logout
Accept: application/json
Authorization: Bearer {{token}}