@token = 3|BWfWUmBujY7D9zR08B0XuSFGQntZyeyLl9sYSwgj12860dea

### =====================================

### Obtener todos los negocios

### GET /api/negocios

### =====================================

GET http://127.0.0.1:8000/api/negocios
Accept: application/json
Authorization: Bearer {{token}}


### =====================================

### Obtener un negocio por ID

### GET /api/negocios/{id}

### =====================================

GET http://127.0.0.1:8000/api/negocios/1
Accept: application/json
Authorization: Bearer {{token}}


### =====================================

### Crear un negocio

### POST /api/negocios

### =====================================

POST http://127.0.0.1:8000/api/negocios
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Tienda Central",
    "direccion": "Av. Principal #123",
    "telefono": "70000000",
    "email": "tienda@mail.com",
    "estado": 1
}


### =====================================

### Actualizar un negocio completo

### PUT /api/negocios/{id}

### =====================================

PUT http://127.0.0.1:8000/api/negocios/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Tienda Central Actualizada",
    "direccion": "Calle Nueva #456",
    "telefono": "71111111",
    "email": "contacto@mail.com",
    "estado": 1
}


### =====================================

### Actualizar solo algunos campos

### PUT /api/negocios/{id}

### =====================================

PUT http://127.0.0.1:8000/api/negocios/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Tienda Modificada",
    "estado": 0
}


### =====================================

### Eliminar un negocio

### DELETE /api/negocios/{id}

### =====================================

DELETE http://127.0.0.1:8000/api/negocios/1
Accept: application/json
Authorization: Bearer {{token}}